default_install_hook_types: [pre-commit, commit-msg]
repos:
    - repo: https://github.com/monchyrcg/qdamos-pre_commit
      rev: 1.0.6
      hooks:
          - id: check-git-name-branch
          - id: check-call-invalid-function
          - id: check-php-cs-fixer
          - id: check-message-commit
          - id: check-phpstan