default_install_hook_types: [pre-commit, commit-msg]
repos:
    - repo: git@github.com:alira-dev/qdamus-pre_commit.git
      rev: 2.0.1
      hooks:
          - id: check-git-name-branch
          - id: check-call-invalid-function
          - id: check-php-cs-fixer
          - id: check-message-commit
          - id: check-phpstan
